# This is a basic workflow to help you get started with Actions

name: azure deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.Azure_Github_Secret_SPN }}

      - name: azure deployment
        run: |
             
             az group create --name AKSBicepRg --location EastUS
          
             az keyvault create --name MyBicep44Kv --resource-group AKSBicepRg --location EastUS

             az keyvault set-policy --name MyBicep44Kv --object-id cb3ad198-df20-47ef-be83-dc4a775a8c46 --secret-permissions get list

             ssh-keygen -t rsa -b 4096 -C "mySSHKey" -f mySSHKey

             az keyvault secret set --name bicepsecretName --vault-name MyBicep44Kv --file mySSHKey.pub --encoding base64

             $sshRSAPublicKey= az keyvault secret show --name bicepsecretName --vault-name MyBicep44Kv --query value -o tsv

             az deployment group create --resource-group AKSBicepRg --template-file ./Azure_AKS.bicep --parameters sshRSAPublicKey="$sshRSAPublicKey"

            

          
   
